apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "metric-service-exporter.fullname" . }}-view-metrics
rules:
- apiGroups:
    - metrics.k8s.io
    - ""
  resources:
    - pods
    - nodes
  verbs:
    - get
    - list
    - watch
