apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "metric-service-exporter.fullname" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
{{- if .Values.extra_labels }}
{{ toYaml .Values.extra_labels | indent 4 }}
{{- end }}